import { NextRequest, NextResponse } from 'next/server';
import { getToken } from 'next-auth/jwt';
import { handleUserMessage } from '@/lib/chat-utils';

export async function POST(request: NextRequest) {
  try {
    // Verify authentication
    const token = await getToken({ 
      req: request, 
      secret: process.env.NEXTAUTH_SECRET || "krishna_divine_wisdom_secret_key" 
    });
    
    if (!token || !token.id) {
      return NextResponse.json(
        { success: false, message: 'Authentication required' },
        { status: 401 }
      );
    }
    
    // Get request data
    const { message, chatId, aiResponse } = await request.json();
    
    if (!message) {
      return NextResponse.json(
        { success: false, message: 'Message is required' },
        { status: 400 }
      );
    }
    
    // Handle the message - create a new chat or add to existing one
    const result = await handleUserMessage({
      userId: token.id as string,
      chatId,
      message,
      aiResponse: aiResponse || "Response will be generated by the AI service"
    });
    
    return NextResponse.json({ 
      success: true, 
      data: result 
    });
    
  } catch (error: any) {
    console.error('Error in chat API:', error);
    return NextResponse.json(
      { success: false, message: error.message || 'An error occurred' },
      { status: 500 }
    );
  }
}